# Generated by Django 4.1 on 2024-08-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_create_test0"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test00",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("num", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Test0",
        ),
    ]
