# Generated by Django 4.1 on 2024-08-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_create_test0"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatabaseList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("group", models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Test0",
        ),
    ]
