# Generated by Django 4.1 on 2024-08-20 08:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_create_test1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1",
        ),
    ]
