# Generated by Django 4.1 on 2024-08-19 08:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_create_test00"),
    ]

    operations = [
        migrations.CreateModel(
            name="Teat4",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name="Test00",
        ),
    ]
