# Generated by Django 4.1 on 2024-08-20 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_create_test0"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test0",
        ),
    ]
