# Generated by Django 4.1 on 2024-08-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_delete_test1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
