# Generated by Django 4.1 on 2024-08-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_databaselist_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="databaselist",
            name="title",
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
