# Generated by Django 4.1 on 2024-08-28 07:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_favorite"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Favorite",
        ),
    ]
