# Generated by Django 4.1 on 2024-09-03 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chemicals", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="other_asssay1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(default="NA", max_length=200)),
                ("comment", models.TextField(null=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
    ]
