# Generated by Django 4.1 on 2024-09-04 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("chemicals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="other_assay2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                (
                    "title",
                    models.CharField(default="NA", help_text="default", max_length=200),
                ),
                ("HFL_1", models.FloatField(help_text="check")),
                ("L929", models.FloatField(help_text="check")),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="other_assay1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(default="NA", max_length=200)),
                ("comment", models.TextField(help_text="default", null=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
    ]
