# Generated by Django 4.1 on 2024-08-23 06:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test0",
        ),
    ]
