# Generated by Django 4.1 on 2024-09-03 07:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0002_initial"),
        ("data", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="other_asssay1",
            new_name="other_assay1",
        ),
    ]
