# Generated by Django 4.1 on 2024-09-04 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0002_initial"),
        ("data", "0002_rename_other_asssay1_other_assay1"),
    ]

    operations = [
        migrations.CreateModel(
            name="other_assay2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(default="NA", max_length=200)),
                ("HFL_1", models.FloatField()),
                ("L929", models.FloatField()),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
    ]
