# Generated by Django 4.1 on 2024-09-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("data", "0003_other_assay2"),
    ]

    operations = [
        migrations.AlterField(
            model_name="other_assay1",
            name="comment",
            field=models.TextField(help_text="default", null=True),
        ),
        migrations.AlterField(
            model_name="other_assay2",
            name="HFL_1",
            field=models.FloatField(help_text="check"),
        ),
        migrations.AlterField(
            model_name="other_assay2",
            name="L929",
            field=models.FloatField(help_text="check"),
        ),
        migrations.AlterField(
            model_name="other_assay2",
            name="title",
            field=models.CharField(default="NA", help_text="default", max_length=200),
        ),
    ]
