# Generated by Django 4.1 on 2024-08-20 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0004_test1_test2_test3"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
        migrations.DeleteModel(
            name="Test3",
        ),
    ]
