# Generated by Django 4.1 on 2024-08-20 09:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0007_test2_alter_test1_table"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
    ]
