# Generated by Django 4.1 on 2024-08-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0009_test1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelTable(
            name="test1",
            table="test1",
        ),
    ]
