# Generated by Django 5.0.1 on 2024-05-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('chem_id', models.AutoField(primary_key=True, serialize=False)),
                ('smiles', models.CharField(max_length=255)),
                ('str_img', models.URLField()),
                ('MW', models.FloatField()),
                ('cLogP', models.FloatField()),
            ],
        ),
    ]
