# Generated by Django 5.1 on 2024-08-26 12:30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chemical',
            fields=[
                ('target', models.CharField(max_length=50)),
                ('chem_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('smiles', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chemicals/')),
                ('MW', models.FloatField(blank=True, null=True)),
                ('cLogP', models.FloatField(blank=True, null=True)),
                ('TPSA', models.FloatField(blank=True, null=True)),
                ('H_donors', models.IntegerField(blank=True, null=True)),
                ('H_acceptors', models.IntegerField(blank=True, null=True)),
                ('lipinski', models.BooleanField(default=False)),
                ('user', models.CharField(max_length=200, null=True)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Test0',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test0',
            },
        ),
        migrations.CreateModel(
            name='CCK_assay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('cell', models.TextField(null=True)),
                ('IC50', models.FloatField(blank=True, help_text='check', null=True)),
                ('Out', models.CharField(help_text='check', max_length=200, null=True)),
                ('comment', models.TextField(null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='CYPInhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cyp_1a2', models.FloatField()),
                ('cyp_2c9', models.FloatField()),
                ('cyp_2c19', models.FloatField()),
                ('cyp_2d6', models.FloatField()),
                ('cyp_3a4', models.FloatField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Cytotoxicity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('VERO', models.FloatField()),
                ('HFL_1', models.FloatField()),
                ('L929', models.FloatField()),
                ('NIH_3T3', models.FloatField()),
                ('CHO_K1', models.FloatField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='in_vivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('cell', models.TextField(null=True)),
                ('does', models.FloatField(blank=True, null=True)),
                ('solvent', models.TextField(null=True)),
                ('inject_date', models.IntegerField(null=True)),
                ('group', models.TextField(null=True)),
                ('comment', models.TextField(null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='LiverMicrosomalStability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mouse', models.FloatField()),
                ('rat', models.FloatField()),
                ('human', models.FloatField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='other_asssay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(default='NA', max_length=200)),
                ('comment', models.TextField(null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacokinetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('max_concentration', models.FloatField(blank=True, null=True)),
                ('tmax', models.FloatField(blank=True, null=True)),
                ('AUC', models.FloatField(blank=True, null=True)),
                ('t_half', models.FloatField(blank=True, null=True)),
                ('Vss', models.FloatField(blank=True, null=True)),
                ('F', models.FloatField(blank=True, null=True)),
                ('CL', models.FloatField(blank=True, null=True)),
                ('Route', models.CharField(max_length=200, null=True)),
                ('user', models.CharField(max_length=200, null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('value', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='SchrödingerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('QPlogS', models.FloatField()),
                ('QPlogHERG', models.FloatField()),
                ('QPPCaco', models.FloatField()),
                ('QPlogBB', models.FloatField()),
                ('QPPMDCK', models.FloatField()),
                ('Metab', models.FloatField()),
                ('QPlogKhsa', models.FloatField()),
                ('HOralAbs', models.FloatField()),
                ('PerHOralAbs', models.FloatField()),
                ('field_11', models.FloatField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Target_Inhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('vitro_at_10', models.FloatField(blank=True, null=True)),
                ('Taret_IC50', models.FloatField(blank=True, null=True)),
                ('comment', models.TextField(null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='Western_blot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('user', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(null=True)),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
        migrations.CreateModel(
            name='invtro_Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='in_vitro/')),
                ('cck_assay', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chemicals.cck_assay')),
                ('others', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chemicals.other_asssay')),
                ('in_target', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chemicals.target_inhibition')),
                ('wb', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='chemicals.western_blot')),
            ],
        ),
    ]
