# Generated by Django 4.1 on 2024-07-22 05:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("userID", models.CharField(default="", max_length=100, unique=True)),
                ("email", models.EmailField(default="", max_length=100, unique=True)),
                ("name", models.CharField(default="", max_length=100)),
                ("roll", models.CharField(default="", max_length=100)),
                ("group", models.CharField(default="", max_length=100)),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Chemical",
            fields=[
                ("target", models.CharField(max_length=50)),
                (
                    "chem_id",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("smiles", models.TextField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="chemicals/"),
                ),
                ("MW", models.FloatField(blank=True, null=True)),
                ("cLogP", models.FloatField(blank=True, null=True)),
                ("TPSA", models.FloatField(blank=True, null=True)),
                ("H_donors", models.IntegerField(blank=True, null=True)),
                ("H_acceptors", models.IntegerField(blank=True, null=True)),
                ("lipinski", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SchrödingerModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("QPlogS", models.FloatField()),
                ("QPlogHERG", models.FloatField()),
                ("QPPCaco", models.FloatField()),
                ("QPlogBB", models.FloatField()),
                ("QPPMDCK", models.FloatField()),
                ("Metab", models.FloatField()),
                ("QPlogKhsa", models.FloatField()),
                ("HOralAbs", models.FloatField()),
                ("PerHOralAbs", models.FloatField()),
                ("field_11", models.FloatField()),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Result",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                ("value", models.FloatField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pharmacokinetic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("cmax", models.FloatField()),
                ("tmax", models.FloatField()),
                ("AUC", models.FloatField()),
                ("t_half", models.FloatField()),
                ("Vss", models.FloatField()),
                ("Vd", models.FloatField()),
                ("BA", models.FloatField()),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LiverMicrosomalStability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("mouse", models.FloatField()),
                ("rat", models.FloatField()),
                ("human", models.FloatField()),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Cytotoxicity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("VERO", models.FloatField()),
                ("HFL_1", models.FloatField()),
                ("L929", models.FloatField()),
                ("NIH_3T3", models.FloatField()),
                ("CHO_K1", models.FloatField()),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CYPInhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("cyp_1a2", models.FloatField()),
                ("cyp_2c9", models.FloatField()),
                ("cyp_2c19", models.FloatField()),
                ("cyp_2d6", models.FloatField()),
                ("cyp_3a4", models.FloatField()),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
    ]
