# Generated by Django 4.1 on 2024-08-20 02:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test00",
        ),
    ]
