# Generated by Django 5.0.1 on 2024-05-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='chem_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='str_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
