# Generated by Django 4.1 on 2024-07-22 05:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chemical",
            name="user",
        ),
    ]
