# Generated by Django 4.1 on 2024-09-04 09:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("chemicals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="favorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="document",
            name="chemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="chemicals.chemical",
            ),
        ),
        migrations.AddField(
            model_name="cytotoxicity",
            name="chemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chemicals.chemical"
            ),
        ),
        migrations.AddField(
            model_name="cypinhibition",
            name="chemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chemicals.chemical"
            ),
        ),
        migrations.AddField(
            model_name="cck_assay",
            name="chemical",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chemicals.chemical"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="favorite",
            unique_together={("user", "item")},
        ),
    ]
