# Generated by Django 4.1 on 2024-08-27 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="western_blot",
            name="comment",
            field=models.TextField(help_text="default", null=True),
        ),
    ]
