# Generated by Django 4.1 on 2024-08-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0002_delete_test00"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "test0",
            },
        ),
    ]
