# Generated by Django 4.1 on 2024-07-25 08:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0002_remove_chemical_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="is_admin",
            new_name="is_superuser",
        ),
    ]
