# Generated by Django 5.0.1 on 2024-05-26 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0003_alter_chemical_clogp_alter_chemical_smiles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chemicals/'),
        ),
        migrations.AlterField(
            model_name='chemical',
            name='str_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
