# Generated by Django 5.0.1 on 2024-05-26 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0004_chemical_image_alter_chemical_str_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chemical',
            name='str_img',
        ),
    ]
