# Generated by Django 4.1 on 2024-07-29 23:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0004_user_groups_user_user_permissions"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pharmacokinetic",
            old_name="BA",
            new_name="CL",
        ),
        migrations.RenameField(
            model_name="pharmacokinetic",
            old_name="Vd",
            new_name="F",
        ),
        migrations.AddField(
            model_name="pharmacokinetic",
            name="Route",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
