# Generated by Django 5.0.1 on 2024-05-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0005_remove_chemical_str_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='target',
            field=models.CharField(default='UNKNOWN', max_length=50),
            preserve_default=False,
        ),
    ]
