# Generated by Django 4.1 on 2024-07-30 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0005_rename_ba_pharmacokinetic_cl_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="user",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="pharmacokinetic",
            name="user",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
