# Generated by Django 4.1 on 2024-07-31 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0007_in_vitro"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="AUC",
            field=models.FloatField(default="NA"),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="CL",
            field=models.FloatField(default="NA"),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="F",
            field=models.FloatField(default="NA"),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="Vss",
            field=models.FloatField(default="NA"),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="cmax",
            field=models.FloatField(default="NA"),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="t_half",
            field=models.FloatField(default="NA"),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="tmax",
            field=models.FloatField(default="NA"),
        ),
    ]
