# Generated by Django 5.0.1 on 2024-05-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0007_alter_chemical_target_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='target',
            field=models.CharField(max_length=50),
        ),
    ]
