# Generated by Django 5.0.1 on 2024-05-27 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0008_alter_chemical_target'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chemical',
            name='chem_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
