# Generated by Django 4.1 on 2024-07-31 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "chemicals",
            "0008_alter_pharmacokinetic_auc_alter_pharmacokinetic_cl_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="in_vitro",
            name="IC50",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="in_vitro",
            name="Taret_IC50",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="in_vitro",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="in_vitro",
            name="vitro_at_10",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="AUC",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="CL",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="F",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="Vss",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="cmax",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="t_half",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="pharmacokinetic",
            name="tmax",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
