# Generated by Django 5.0.1 on 2024-05-27 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0009_alter_chemical_chem_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacokinetic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cmax', models.FloatField()),
                ('tmax', models.FloatField()),
                ('AUC', models.FloatField()),
                ('t_half', models.FloatField()),
                ('Vss', models.FloatField()),
                ('Vd', models.FloatField()),
                ('BA', models.FloatField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
    ]
