# Generated by Django 4.1 on 2024-07-31 05:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0009_alter_in_vitro_ic50_alter_in_vitro_taret_ic50_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="in_vitro",
            name="title",
            field=models.CharField(default="NA", max_length=200),
        ),
    ]
