# Generated by Django 4.1 on 2024-08-21 00:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0010_test2_alter_test1_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="test2",
            table="test2",
        ),
    ]
