# Generated by Django 4.1 on 2024-07-31 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0011_alter_in_vitro_out_alter_in_vitro_cell"),
    ]

    operations = [
        migrations.AlterField(
            model_name="in_vitro",
            name="Out",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
