# Generated by Django 4.1 on 2024-07-31 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0012_alter_in_vitro_out"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="in_vitro",
            name="image",
        ),
        migrations.CreateModel(
            name="In_vitro_Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="in_vitro/")),
                (
                    "in_vitro_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="chemicals.in_vitro",
                    ),
                ),
            ],
        ),
    ]
