# Generated by Django 5.0.1 on 2024-05-29 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0012_schrödingermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='H_acceptors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='H_donors',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='TPSA',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chemical',
            name='lipinski',
            field=models.BooleanField(default=False),
        ),
    ]
