# Generated by Django 4.1 on 2024-08-21 02:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0012_테스트123"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
        migrations.DeleteModel(
            name="테스트123",
        ),
    ]
