# Generated by Django 5.0.1 on 2024-05-29 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0013_chemical_h_acceptors_chemical_h_donors_chemical_tpsa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiverMicrosomalStability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('mouse', models.FloatField()),
                ('rat', models.FloatField()),
                ('human', models.FloatField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
    ]
