# Generated by Django 4.1 on 2024-07-31 08:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0013_remove_in_vitro_image_in_vitro_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="in_vitro",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="in_vitro/"),
        ),
        migrations.DeleteModel(
            name="In_vitro_Image",
        ),
    ]
