# Generated by Django 4.1 on 2024-08-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0013_delete_test1_delete_test2_delete_테스트123"),
    ]

    operations = [
        migrations.CreateModel(
            name="Other123",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
