# Generated by Django 4.1 on 2024-08-01 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0014_in_vitro_image_delete_in_vitro_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cypinhibition",
            name="user",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="cytotoxicity",
            name="user",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="livermicrosomalstability",
            name="user",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
