# Generated by Django 4.1 on 2024-08-21 02:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0014_other123"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test666",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "test666",
            },
        ),
        migrations.AlterModelTable(
            name="other123",
            table="other123",
        ),
    ]
