# Generated by Django 5.0.1 on 2024-05-29 22:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0014_livermicrosomalstability'),
    ]

    operations = [
        migrations.CreateModel(
            name='CYPInhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('cyp_1a2', models.FloatField()),
                ('cyp_2c9', models.FloatField()),
                ('cyp_2c19', models.FloatField()),
                ('cyp_2d6', models.FloatField()),
                ('cyp_3a4', models.FloatField()),
                ('chemical', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chemicals.chemical')),
            ],
        ),
    ]
