# Generated by Django 5.0.1 on 2024-05-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0015_cypinhibition'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_1',
            new_name='HOralAbs',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_10',
            new_name='Metab',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_12',
            new_name='PerHOralAbs',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_13',
            new_name='QPPCaco',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_14',
            new_name='QPPMDCK',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_15',
            new_name='QPlogBB',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_16',
            new_name='QPlogHERG',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_17',
            new_name='QPlogKhsa',
        ),
        migrations.RenameField(
            model_name='schrödingermodel',
            old_name='field_18',
            new_name='QPlogS',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_19',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_2',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_20',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_3',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_4',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_5',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_6',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_7',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_8',
        ),
        migrations.RemoveField(
            model_name='schrödingermodel',
            name='field_9',
        ),
    ]
