# Generated by Django 4.1 on 2024-08-01 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0016_result_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="CCK_assay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("cell", models.TextField(null=True)),
                ("IC50", models.FloatField(blank=True, null=True)),
                ("Out", models.CharField(max_length=200, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="in_vitro/"),
                ),
                ("comment", models.TextField(null=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="other",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("title", models.CharField(default="NA", max_length=200)),
                ("comment", models.TextField(null=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Target_Inhibition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("vitro_at_10", models.FloatField(blank=True, null=True)),
                ("Taret_IC50", models.FloatField(blank=True, null=True)),
                ("comment", models.TextField(null=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Western_blot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("user", models.CharField(max_length=200, null=True)),
                ("comment", models.TextField(null=True)),
                (
                    "chemical",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="chemicals.chemical",
                    ),
                ),
            ],
        ),
        migrations.RenameModel(
            old_name="result_Image",
            new_name="CCK_Image",
        ),
        migrations.DeleteModel(
            name="In_vitro",
        ),
        migrations.AlterField(
            model_name="cck_image",
            name="result_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="chemicals.cck_assay",
            ),
        ),
    ]
