# Generated by Django 4.1 on 2024-08-21 07:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0017_test3"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Other123",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
        migrations.DeleteModel(
            name="Test3",
        ),
        migrations.DeleteModel(
            name="Test666",
        ),
    ]
