# Generated by Django 4.1 on 2024-08-02 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0017_cck_assay_other_target_inhibition_western_blot_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cck_assay",
            name="image",
        ),
    ]
