# Generated by Django 4.1 on 2024-08-02 01:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0018_remove_cck_assay_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cck_image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
