# Generated by Django 4.1 on 2024-08-21 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0019_test1234"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test22",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
