# Generated by Django 4.1 on 2024-08-02 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0020_rename_result_id_cck_image_cck_assay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cck_image",
            name="image",
            field=models.ImageField(upload_to="cck/"),
        ),
    ]
