# Generated by Django 4.1 on 2024-08-21 07:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0020_test22"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1234",
        ),
        migrations.DeleteModel(
            name="Test22",
        ),
    ]
