# Generated by Django 4.1 on 2024-08-05 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0021_alter_cck_image_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="cck_image",
            name="in_target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="chemicals.target_inhibition",
            ),
        ),
        migrations.AddField(
            model_name="cck_image",
            name="others",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="chemicals.other",
            ),
        ),
        migrations.AddField(
            model_name="cck_image",
            name="wb",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="chemicals.western_blot",
            ),
        ),
        migrations.AlterField(
            model_name="cck_image",
            name="cck_assay",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="chemicals.cck_assay",
            ),
        ),
        migrations.AlterField(
            model_name="cck_image",
            name="image",
            field=models.ImageField(upload_to="in_vitro/"),
        ),
    ]
