# Generated by Django 4.1 on 2024-08-21 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0022_test123456"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test2",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "test2",
            },
        ),
        migrations.AlterModelTable(
            name="test123456",
            table="test123456",
        ),
    ]
