# Generated by Django 4.1 on 2024-08-05 01:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "chemicals",
            "0022_cck_image_in_target_cck_image_others_cck_image_wb_and_more",
        ),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CCK_Image",
            new_name="invtro_Image",
        ),
    ]
