# Generated by Django 4.1 on 2024-08-05 05:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0023_rename_cck_image_invtro_image"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="other",
            new_name="other_asssay",
        ),
    ]
