# Generated by Django 4.1 on 2024-08-21 08:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0023_test2_alter_test123456_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Testa01",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("num", models.IntegerField()),
            ],
            options={
                "db_table": "testa01",
            },
        ),
        migrations.DeleteModel(
            name="Test123456",
        ),
        migrations.DeleteModel(
            name="Test2",
        ),
    ]
