# Generated by Django 4.1 on 2024-08-21 08:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0024_testa01_delete_test123456_delete_test2"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Testa01",
        ),
    ]
