# Generated by Django 4.1 on 2024-08-13 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0024_rename_other_other_asssay"),
    ]

    operations = [
        migrations.AddField(
            model_name="chemical",
            name="datetime",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
