# Generated by Django 4.1 on 2024-08-21 08:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0026_test3"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test3",
        ),
    ]
