# Generated by Django 4.1 on 2024-08-21 08:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0029_test3"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Teat2",
        ),
        migrations.DeleteModel(
            name="Test3",
        ),
    ]
