# Generated by Django 4.1 on 2024-08-21 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0030_delete_teat2_delete_test3"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test1",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
    ]
