# Generated by Django 4.1 on 2024-08-21 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0033_test1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test1",
        ),
    ]
