# Generated by Django 4.1 on 2024-08-22 08:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0035_test1"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test0",
        ),
        migrations.DeleteModel(
            name="Test1",
        ),
    ]
