# Generated by Django 4.1 on 2024-08-23 00:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0037_test0"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Test0",
        ),
    ]
