# Generated by Django 4.1 on 2024-08-23 00:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0038_delete_test0"),
    ]

    operations = []
