# Generated by Django 4.1 on 2024-08-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0040_auto_20240823_0929"),
    ]

    operations = [
        migrations.CreateModel(
            name="Test0",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "test0",
            },
        ),
        migrations.AddField(
            model_name="cck_assay",
            name="is_check",
            field=models.BooleanField(default=False),
        ),
    ]
