# Generated by Django 4.1 on 2024-08-23 06:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chemicals", "0041_test0_cck_assay_is_check"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cck_assay",
            name="is_check",
        ),
        migrations.AlterField(
            model_name="cck_assay",
            name="IC50",
            field=models.FloatField(blank=True, help_text="check", null=True),
        ),
        migrations.AlterField(
            model_name="cck_assay",
            name="Out",
            field=models.CharField(help_text="Scheck", max_length=200, null=True),
        ),
    ]
